// jquery
import 'jquery';
// semantic-ui
import 'semantic-ui/dist/semantic';
import 'semantic-ui/dist/semantic.css';
// angular
import 'angular/angular-csp.css';
import 'angular';
import '@angular/router/angular1/angular_1_router.js';
import 'angular-component-router-active';
